Flake-Modules:
  - changed-files:
      - any-glob-to-any-file: flake-modules/**/*
Config:
  - changed-files:
      - any-glob-to-any-file: config/**/*
Library:
  - changed-files:
      - any-glob-to-any-file: lib/**/*
Packages:
  - changed-files:
      - any-glob-to-any-file: packages/**/*
GitHub-Action:
  - changed-files:
      - any-glob-to-any-file: .github/workflows/*
